## coin 자료 처리하기

## I. 날짜별, 코인별 영어 합치기

In [ ]:
!pip install pymysql
!pip install sqlalchemy
!pip install mysqlclient

Collecting pymysql
  Downloading PyMySQL-1.0.2-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 1.5 MB/s
Installing collected packages: pymysql
Successfully installed pymysql-1.0.2
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.7/dist-packages (1.4.27)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from sqlalchemy) (4.8.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from sqlalchemy) (1.1.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy) (3.6.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy) (3.10.0.2)
Collecting mysqlclient
  Downloading mysqlclient-2.1.0.tar.gz (87 kB)
     |████████████████████████████████| 87 kB 6.5 MB/s
Building wheels for collected packages: mysqlclient
  Building wheel for mysqlclient (setup.py) ... done
  Created wheel for mysqlclient: filename=mysqlclient-2.1.0-cp37-cp37m-linux_x86_64.whl size=99959 sha256=586ae078eb596514c25869d567c290a860369b250965fffe294478373471d4eb
  Stored in directory: /root/.cache/pip/wheels/97/d4/df/08cd6e1fa4a8691b268ab254bd0fa589827ab5b65638c010b4
Successfully built mysqlclient
Installing collected packages: mysqlclient
Successfully installed mysqlclient-2.1.0

In [ ]:
import warnings
warnings.filterwarnings('ignore')
import time
import datetime
import pymysql
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
import pymysql
import matplotlib.pyplot as plt
import seaborn as sns

import itertools
import operator

import base64
from io import BytesIO

from datetime import datetime, timedelta

In [ ]:
db = pymysql.connect(host=, charset='utf8')
cursor = db.cursor(pymysql.cursors.DictCursor)
sql = 'SELECT * FROM coin'
cursor.execute(sql)
result = cursor.fetchall()
DF = pd.DataFrame(result)

In [ ]:
DF['coin'].count()

2756

### 1) 일단 코인별로

In [ ]:
crypto_name_e = ['ADA','BTC','BCH','DOGE','EOS','ETH','OMG','SNT','XRP']
crypto_name_k = ['ada','btc','bch','doge','eos','eth','omg','snt','xrp']

In [ ]:
X = []

for i in range(len(DF)):


  if DF['coin'][i] == 'BCH':
    a = DF['date'][i]
    b = DF['num'][i]
    c = DF['s'][i]
    d = DF['lang'][i]
    e = DF['coin'][i]

    data = [a,b,c,d,e]
    X.append(data)


BCH = pd.DataFrame(X)
BCH.columns = ['date','num','s','lang','coin']
BCH

         date  num         s lang coin
0  2021-11-17  219  1.388128  eng  BCH
1  2021-11-19  228  1.377193  eng  BCH
2  2021-11-22  117  1.333333  eng  BCH

In [ ]:
X = []

for i in range(len(DF)):


  if DF['coin'][i] == 'ada':
    a = DF['date'][i]
    b = DF['num'][i]
    c = DF['s'][i]
    d = DF['lang'][i]
    e = DF['coin'][i]

    data = [a,b,c,d,e]
    X.append(data)

ada = pd.DataFrame(X)
ada.columns = ['date','num','s','lang','coin']
ada

           date  num         s lang coin
0    2021-02-20   18  0.555556  kor  ada
1    2021-02-21   16  0.875000  kor  ada
2    2021-02-22    9  0.666667  kor  ada
3    2021-02-23   15  0.800000  kor  ada
4    2021-02-24    7  0.285714  kor  ada
..          ...  ...       ...  ...  ...
257  2021-11-17   27  0.777778  kor  ada
258  2021-11-18    7  0.857143  kor  ada
259  2021-11-19    6  0.500000  kor  ada
260  2021-11-20   11  0.454545  kor  ada
261  2021-11-21    4  0.000000  kor  ada

[262 rows x 5 columns]

## 2) 생각점
- 일단 영어를 기준으로 서비스 해야한다
- 주말이나 과거대이터에 영어가 빠지면 이상하니 영어를 기준으로 조합
- 즉, ADA 에 ada 값을 집어넣어야 한다

In [ ]:
X = []

for j in range(len(ADA)):

  for i in range(len(ada)):

    if ADA['date'][j] == ada['date'][i]:
      a = ADA['date'][j]
      b = ADA['num'][j]
      c = ADA['s'][j]
      d = ada['num'][i]
      e = ada['s'][i]
      f = ADA['coin'][j]

      x = [a,b,c,d,e,f]
      X.append(x)

ADA1 = pd.DataFrame(X)
ADA1.columns = ['date','num_e','s_e','num_k','s_k','coin']
ADA1

         date   num_e       s_e  num_k       s_k coin
0  2021-11-17  135451  1.444862     27  0.777778  ADA
1  2021-11-19  147170  1.462798      6  0.500000  ADA

- 위의 결과는 영어는 3일있고 한글은 그에 겹치는 날이 2날밖에 없어서

## 3) 모든 코인에 대해 일반화

In [ ]:
crypto_name_e = ['ADA','BTC','BCH','DOGE','EOS','ETH','OMG','SNT','XRP']
crypto_name_k = ['ada','btc','bch','doge','eos','eth','omg','snt','xrp']

for j in crypto_name_e:
  
  X = []

  for i in range(len(DF)):


    if j == DF['coin'][i]:
      a = DF['date'][i]
      b = DF['num'][i]
      c = DF['s'][i]
      d = DF['lang'][i]
      e = DF['coin'][i]

      data = [a,b,c,d,e]
      X.append(data)


  globals()[j] = pd.DataFrame(X)
  globals()[j].columns = ['date','num','s','lang','coin']

#
for j in crypto_name_k:
  
  X = []

  for i in range(len(DF)):


    if DF['coin'][i] == j:
      a = DF['date'][i]
      b = DF['num'][i]
      c = DF['s'][i]
      d = DF['lang'][i]
      e = DF['coin'][i]

      data = [a,b,c,d,e]
      X.append(data)

  globals()[j] = pd.DataFrame(X)
  globals()[j].columns = ['date','num','s','lang','coin']

## 4) 모든 코인에 대해 일반화 후 하나로 합치기

In [ ]:
crypto_name_e = ['ADA','BTC','BCH','DOGE','EOS','ETH','OMG','SNT','XRP']
crypto_name_k = ['ada','btc','bch','doge','eos','eth','omg','snt','xrp']

for j in crypto_name_e:
  
  X = []

  for i in range(len(DF)):


    if j == DF['coin'][i]:
      a = DF['date'][i]
      b = DF['num'][i]
      c = DF['s'][i]
      d = DF['lang'][i]
      e = DF['coin'][i]

      data = [a,b,c,d,e]
      X.append(data)


  globals()[j] = pd.DataFrame(X)
  globals()[j].columns = ['date','num','s','lang','coin']

#
for j in crypto_name_k:
  
  X = []

  for i in range(len(DF)):


    if DF['coin'][i] == j:
      a = DF['date'][i]
      b = DF['num'][i]
      c = DF['s'][i]
      d = DF['lang'][i]
      e = DF['coin'][i]

      data = [a,b,c,d,e]
      X.append(data)

  globals()[j] = pd.DataFrame(X)
  globals()[j].columns = ['date','num','s','lang','coin']

crypto_e = [ADA,BTC,BCH,DOGE,EOS,ETH,OMG,SNT,XRP]
crypto_k = [ada,btc,bch,doge,eos,eth,omg,snt,xrp]

X = []

for k,l in zip(crypto_e,crypto_k):
  
  for j in range(len(k)):

    for i in range(len(l)):

      if k['date'][j] == l['date'][i]:
        a = k['date'][j]
        b = k['num'][j]
        c = k['s'][j]
        d = l['num'][i]
        e = l['s'][i]
        f = k['coin'][j]

        x = [a,b,c,d,e,f]
        X.append(x)

DF_buble = pd.DataFrame(X)
DF_buble.columns = ['date','num_e','s_e','num_k','s_k','coin']
DF_buble

          date   num_e       s_e  num_k       s_k  coin
0   2021-11-17  135451  1.444862     27  0.777778   ADA
1   2021-11-19  147170  1.462798      6  0.500000   ADA
2   2021-11-17   17500  1.423029      9  1.111111   BTC
3   2021-11-19   24485  1.402532      4  0.000000   BTC
4   2021-11-17     219  1.388128     56  0.839286   BCH
5   2021-11-19     228  1.377193     16  0.812500   BCH
6   2021-11-17    7475  1.429967     58  0.724138  DOGE
7   2021-11-19    6338  1.384664     18  0.944444  DOGE
8   2021-11-17     968  1.369835     95  1.073684   EOS
9   2021-11-19     942  1.371550     31  0.935484   EOS
10  2021-11-19   54015  1.435842      1  2.000000   ETH
11  2021-11-17      39  1.333333      3  0.666667   OMG
12  2021-11-17      92  1.260870      6  1.000000   SNT
13  2021-11-19     137  1.518248      3  0.666667   SNT
14  2021-11-17    5615  1.432057     57  0.859649   XRP
15  2021-11-19    6826  1.417521     32  0.718750   XRP